# Generated by Django 5.1.1 on 2024-10-23 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaDjangoApp2', '0002_suplementos_ofertaporcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplementos',
            name='descripcion',
            field=models.CharField(max_length=1000),
        ),
    ]
