# Generated by Django 5.1.1 on 2024-10-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaDjangoApp2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suplementos',
            name='ofertaPorcentaje',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
