# Generated by Django 5.1.1 on 2024-10-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaDjangoApp2', '0003_alter_suplementos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplementos',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
